name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
      working-directory: ./v4.0/MouseWrap4
    - name: make
      run: make
      working-directory: ./v4.0/MouseWrap4
    - name: make check
      run: make check
      working-directory: ./v4.0/MouseWrap4
    - name: make distcheck
      run: make distcheck
      working-directory: ./v4.0/MouseWrap4
