name: C Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build application
        shell: bash
        run: make CC=gcc all

      - name: Run Unity tests
        shell: bash
        run: make CC=gcc test
